"""
TITANS 扩展包 - DEATHKNIGHT
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_457:
    """悼词宣诵者 - Eulogizer
    [x]<b>Battlecry:</b> Spend 3 <b>Corpses</b> to deal 3 damage. <b>Forge:</b> Gain them instead.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_735:
    """北境导航 - Northern Navigation
    <b>Discover</b> a spell from your deck. If it's a Frost spell, <b>Freeze</b> a random enemy minion.
    """
    pass


class TTN_736:
    """兵主之杖 - Staff of the Primus
    After your hero attacks, shuffle a random Plague into your opponent's deck.
    """
    pass


class YOG_511:
    """黑暗符文 - Runes of Darkness
    <b>Discover</b> a weapon. Spend 3 <b>Corpses</b> to give it +1/+1.
    """
    pass


class YOG_512:
    """秽病行尸 - Sickly Grimewalker
    [x]After you summon an  Undead, give it <b>Poisonous</b>.
    """
    pass


# RARE

class TTN_454:
    """殉船 - Down with the Ship
    Deal $3 damage. Shuffle two random Plagues into your opponent's deck.
    """
    pass


class TTN_455:
    """墓地叛徒 - Tomb Traitor
    <b>Battlecry:</b> Destroy a Plague in your opponent's deck to deal 3 damage to all enemy minions.
    """
    pass


class TTN_744:
    """严寒冰封 - Frozen Over
    [x]Both players draw 2 cards. Your opponent can not play them next turn.
    """
    pass


class YOG_513:
    """邪恶魂笼 - Sinister Soulcage
    [x]Give a friendly Undead +2/+2. Spend 5 <b>Corpses</b> to summon a copy of it.
    """
    pass


# EPIC

class TTN_450:
    """困苦的克瓦迪尔 - Distressed Kvaldir
    <b>Deathrattle:</b> Shuffle two random Plagues into your opponent's deck.
    """
    pass


class TTN_459:
    """链缚守护者 - Chained Guardian
    [x]<b><b>Rush</b>, Reborn</b> Costs (1) less for each Plague shuffled into the  enemy deck this game.
    """
    pass


# LEGENDARY

class TTN_737:
    """兵主 - The Primus
    <b>Titan</b> After this uses an ability, <b>Discover</b> a card with that Rune.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_850:
    """海拉 - Helya
    [x]<b>Battlecry:</b> Shuffle all three Plagues into your opponent's deck. Plagues they draw this game are unending.
    """
    pass


