"""
TITANS 扩展包 - DEMONHUNTER
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_843:
    """艾瑞达欺诈者 - Eredar Deceptor
    每当你抽一张牌时，召唤一个1/1并具有<b>突袭</b>的恶魔。
    """
    events = Draw(CONTROLLER).on(Summon(CONTROLLER, "TTN_843t"))


class TTN_843t:
    """Imp"""
    atk = 1
    health = 1
    rush = True
    race = Race.DEMON


class TTN_844:
    """阿古尼特魔像 - Argunite Golem
    在本回合中你每抽一张牌，便拥有+1攻击力。
    """
    events = Draw(CONTROLLER).on(Buff(SELF, "TTN_844e"))

class TTN_844e:
    tags = {GameTag.ATK: 1}
    events = TurnEnd(CONTROLLER).on(Destroy(SELF))


class TTN_861:
    """阿古斯的信徒 - Disciple of Argus
    <b>亡语：</b>召唤两个2/2并具有<b>嘲讽</b>的元素。
    """
    deathrattle = Summon(CONTROLLER, "TTN_861t") * 2

class TTN_861t:
    """Tantilizing Elemental"""
    atk = 2
    health = 2
    taunt = True
    race = Race.ELEMENTAL


class YOG_401:
    """时间咒符 - Sigil of Time
    在你的下个回合开始时，额外抽三张牌。
    """
    play = Buff(CONTROLLER, "YOG_401e")

class YOG_401e:
    events = OWN_TURN_BEGIN.on(Draw(CONTROLLER, 3), Destroy(SELF))


class YOG_402:
    """摧心魔 - Mindbender
    <b>战吼：</b>在本回合中你每抽一张牌，造成1点伤害。0<i>（造成0点）</i>
    """
    def play(self):
        # 伤害 = 本回合抽牌数 * 1
        damage = self.controller.cards_drawn_this_turn
        yield Hit(TARGET, damage)
    requirements = {PlayReq.REQ_TARGET_TO_PLAY: True}


# RARE

class TTN_840:
    """晶石雕像 - Crystalline Statue
    <b>突袭</b>。起始<b>休眠</b>状态。在你抽四张牌后唤醒。
    """
    rush = True
    dormant = True 
    events = Draw(CONTROLLER).on(
        UpdateProgress(SELF, 1),
        If(Attr(SELF, GameTag.PROGRESS) >= 4, Awaken(SELF))
    )


class TTN_841:
    """势如破竹 - Momentum
    在本回合中，使你的英雄获得+4攻击力。在本回合中你每抽一张牌，本牌的法力值消耗便 减少（1）点。
    """
    play = Buff(FRIENDLY_HERO, "TTN_841e")
    cost_mod = lambda self, i: -self.controller.cards_drawn_this_turn
class TTN_841e:
    tags = {GameTag.ATK: 4}
    events = TurnEnd(CONTROLLER).on(Destroy(SELF))


class TTN_865:
    """举世之重 - Weight of the World
    抽两张牌。<b>锻造：</b>先抽若干数量的牌，直到你的手牌数量等同于你对手的手牌数量。
    """
    play = Draw(CONTROLLER, 2)


class TTN_865t:
    """举世之重 - Weight of the World (Forged)"""
    def play(self):
        diff = len(self.controller.opponent.hand) - len(self.controller.hand)
        if diff > 0:
            yield Draw(CONTROLLER, diff)
        yield Draw(CONTROLLER, 2)


class YOG_521:
    """萨隆铁矿蹒跚者 - Saronite Shambler
    <b>战吼：</b>在本局对战中，如果你施放过5个或以上法术，使你的英雄在本回合中获得+4攻击力。@<i>（还剩{0}个！）</i>@<i>（已经就绪！）</i>
    """
    def play(self):
        # 检查本局对战施放的法术数量
        # 玩家追踪 `spent_mana_on_spells_this_game` 但不直接追踪数量?
        # 玩家有 `cards_played_this_game`.
        # 在 `cards_played_this_game` 中统计 type == SPELL 的卡牌数量
        # 注意: `cards_played_this_game` 是一个 CardList.
        spells_cast = len([c for c in self.controller.cards_played_this_game if c.type == CardType.SPELL])
        if spells_cast >= 5:
            yield Buff(FRIENDLY_HERO, "YOG_521e")

class YOG_521e:
    tags = {GameTag.ATK: 4}
    events = TurnEnd(CONTROLLER).on(Destroy(SELF))


# EPIC

class TTN_845:
    """符文装饰 - Runic Adornment
    <b>发现</b>一张法力值消耗小于或等于（3）点的法术牌，将2张具有<b>抽到时施放</b>的复制洗入你的牌库。
    """
    # 筛选条件：法术，法力值消耗 <= 3
    def play(self):
        yield Discover(CONTROLLER, RANDOM(FRIENDLY_DECK + SPELL + (COST <= 3))).then(
            TTN_845_ShuffleCopies(Give.CARD)
        )

class TTN_845_ShuffleCopies(TargetedAction):
    def do(self, source, target, card):
        copies = [card.copy(), card.copy()]
        # 赋予"抽到时施放"效果的附魔
        # 我们需要模拟 "Casts When Drawn"。
        # 我们可以添加一个处理此逻辑的附魔，或者依赖 CastWhenDrawn 助手（如果我们能注入事件）。
        # 但向实例注入事件比较困难。
        # 最好的方法：用一个带有 CastWhenDrawn 逻辑的附魔来 buff 这些卡牌。
        for copy in copies:
            copy.buffs.append(source.controller.card("TTN_845e"))
            # 注意: 在 SetAside/Deck 中 buff 卡牌可能需要适当的 `Buff` 动作?
            # 或者如果不在场上，只需追加到 buffs 列表。
            # 使用 `Buff` 动作更安全。
        
        source.game.queue_actions(source, [Buff(copies, "TTN_845e")])
        source.game.queue_actions(source, [Shuffle(source.controller, copies)])

class TTN_845e:
    """赋予抽到时施放的附魔"""
    tags = {GameTag.CASTS_WHEN_DRAWN: True}
    # CastWhenDrawn(Action) -> Draw(CONTROLLER, SELF).after(Action, Draw(CONTROLLER))
    # 这里的 Action 是 CastSpell(OWNER).
    events = CastWhenDrawn(CastSpell(OWNER))


class TTN_866:
    """神秘恐魔 - Mythical Terror
    <b>吸血</b>。在你的回合结束时，迫使所有敌方随从攻击本随从。
    """
    lifesteal = True
    # 强制攻击：Attack(Source, Target)。源攻击目标。
    # 敌方随从攻击本随从。
    # 事件循环遍历敌方随从。
    events = OWN_TURN_END.on(
        Foreach(ENEMY_MINIONS, Attack(Foreach.CARD, SELF))
    )


# LEGENDARY

class TTN_842:
    """永恒者尤顿 - Jotun, the Eternal
    <b>战吼：</b>在本局对战的剩余时间内，对敌人施放你每回合抽到的第一张法术牌的复制。
    """
    play = Buff(CONTROLLER, "TTN_842e")

class TTN_842e:
    # 逻辑：
    # 1. 新回合 -> 重置"已触发"标记。
    # 2. 抽牌 -> 如果是法术且未触发 -> 随机对敌人施放复制 -> 设置已触发。
    # 需要一个属性来追踪已触发状态。在附魔本身上使用一个 Tag?
    # 或者如果是有状态的，使用脚本变量?
    # 让我们在 SELF (附魔) 上使用一个虚拟 Tag。
    # GameTag.LOCKED 是通用的，但可能引起混淆。
    # 可以使用 `powered_up` (GameTag.POWERED_UP) 作为布尔标记。
    
    events = [
        # 在每个回合开始时重置? 文本说 "your turn"。"First spell you draw EACH turn" (通常意味着你的每个回合)。
        # 英文: "cast a copy of the first spell you draw each turn".
        # 让我们假设是拥有者的回合。
        OWN_TURN_BEGIN.on(SetTag(SELF, {GameTag.POWERED_UP: False})),
        
        Draw(CONTROLLER).on(
            If(And(
                Is(Draw.CARD, SPELL), 
                Not(Tag(SELF, GameTag.POWERED_UP)),
                CurrentPlayer(CONTROLLER) # 确保是我们的回合 (如果 "each turn" 意味着那样)
               ),
               [
                   # 施放复制
                   CastSpell(CopyOf(Draw.CARD), TARGET=RANDOM(ENEMY_CHARACTERS)),
                   # 设置标记
                   SetTag(SELF, {GameTag.POWERED_UP: True})
               ]
            )
        )
    ]


class TTN_862:
    """翠绿之星阿古斯 - Argus, the Emerald Star
    <b>泰坦</b> 本随从左边的随从均拥有<b>突袭</b>，本随从右边的随从均拥有<b>吸血</b>。
    
    核心机制：
    - 使用 LEFT_OF(SELF) 和 RIGHT_OF(SELF) 选择器分别选择左右两侧的随从
    - 使用 Refresh 机制动态应用光环效果
    - 左侧随从获得突袭 (RUSH)
    - 右侧随从获得吸血 (LIFESTEAL)
    - 参考火舌图腾 (EX1_565) 的实现模式
    """
    titan = True
    
    # 位置光环：左侧随从获得突袭，右侧随从获得吸血
    update = [
        Refresh(LEFT_OF(SELF), buff="TTN_862e_left"),   # 左侧随从：突袭
        Refresh(RIGHT_OF(SELF), buff="TTN_862e_right")  # 右侧随从：吸血
    ]
    
    # 泰坦技能
    def titan_ability_1(self):
        """雕琢晶石：发现一张亡语随从牌，法力值消耗减少（3）点"""
        yield Discover(CONTROLLER, RandomCollectible(deathrattle=True, type=CardType.MINION)).then(
            Give(CONTROLLER, Discover.CARD),
            Buff(Give.CARD, "TTN_862t1e")
        )

    def titan_ability_2(self):
        """力量展现：使你手牌中的所有随从牌的法力值消耗减少（2）点"""
        yield Buff(FRIENDLY_HAND + MINION, "TTN_862t3e")

    def titan_ability_3(self):
        """阿古尼特大军：召唤四个2/2并具有嘲讽的元素"""
        yield Summon(CONTROLLER, "TTN_862t4") * 4

class TTN_862e_left:
    """阿古斯的祝福 (左侧) - 突袭"""
    tags = {GameTag.RUSH: True}

class TTN_862e_right:
    """阿古斯的祝福 (右侧) - 吸血"""
    tags = {GameTag.LIFESTEAL: True}

class TTN_862t1e:
    """大地之晶 - Cost reduced by (3)"""
    tags = {GameTag.COST: -3}

class TTN_862t3e:
    """阿古斯的祝福 - Cost reduced by (2)"""
    tags = {GameTag.COST: -2}

class TTN_862t4:
    """晶石元素 - Crystal Elemental"""
    atk = 2
    health = 2
    taunt = True
    race = Race.ELEMENTAL

