"""
TITANS 扩展包 - DEMONHUNTER
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_843:
    """艾瑞达欺诈者 - Eredar Deceptor
    Whenever you draw a card, summon a 1/1 Demon with <b>Rush</b>.
    """
    pass


class TTN_844:
    """阿古尼特魔像 - Argunite Golem
    [x]Has +1 Attack for each card you've drawn this turn.
    """
    pass


class TTN_861:
    """阿古斯的信徒 - Disciple of Argus
    [x]<b>Deathrattle:</b> Summon two 2/2 Elementals with <b>Taunt</b>.
    """
    pass


class YOG_401:
    """时间咒符 - Sigil of Time
    At the start of your next turn, draw 3 additional cards.
    """
    pass


class YOG_402:
    """摧心魔 - Mindbender
    <b>Battlecry:</b> Deal 1 damage for each card you have drawn this turn.@ <i>(@)</i>
    """
    pass


# RARE

class TTN_840:
    """晶石雕像 - Crystalline Statue
    <b>Rush</b>. Starts <b>Dormant</b>. After you draw 4 cards, this awakens.
    """
    pass


class TTN_841:
    """势如破竹 - Momentum
    Give your hero +4 Attack this turn. Costs (1) less for each card you've drawn this turn.
    """
    pass


class TTN_865:
    """举世之重 - Weight of the World
    Draw 2 cards. <b>Forge:</b> Draw cards until you have as many in hand as your opponent first.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_521:
    """萨隆铁矿蹒跚者 - Saronite Shambler
    [x]<b>Battlecry:</b> If you've cast 5 or more spells this game, give your hero +4 Attack this turn. @ <i>({0} left!)</i>@ <i>(Ready!)</i>
    """
    pass


# EPIC

class TTN_845:
    """符文装饰 - Runic Adornment
    <b>Discover</b> a spell that costs (3) or less. Shuffle 2 copies into your deck that <b>Cast When Drawn</b>.
    """
    pass


class TTN_866:
    """神秘恐魔 - Mythical Terror
    [x]<b>Lifesteal</b> At the end of your turn, force all enemy minions to attack this.
    """
    pass


# LEGENDARY

class TTN_842:
    """永恒者尤顿 - Jotun, the Eternal
    [x]<b>Battlecry:</b> For the rest of the game, cast a copy of the first spell you draw each turn at enemies.
    """
    pass


class TTN_862:
    """翠绿之星阿古斯 - Argus, the Emerald Star
    [x]<b>Titan</b> Minions to the left of this have <b>Rush</b>, and ones to the right have <b>Lifesteal</b>.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


