"""
TITANS 扩展包 - DRUID
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_950:
    """林木幼苗 - Forest Seedlings
    Summon two 1/1 Saplings. <i>(Blossoms in 2 turns.)</i>
    """
    pass


class TTN_954:
    """栽培 - Cultivation
    Give your minions +2/+2. Costs (1) less for each Treant you've summoned this game.
    """
    pass


class TTN_955:
    """生命缚誓者的礼物 - Lifebinder's Gift
    <b>Choose One -</b> Get 2 random Nature spells; or Reduce the Cost of spells in your hand by (1).
    """
    pass


class YOG_403:
    """空中施肥者 - Aerosoilizer
    <b>Battlecry and Deathrattle:</b> Summon a 2/2 Treant.
    """
    pass


# RARE

class TTN_927:
    """护园森灵 - Conservator Nymph
    <b>Battlecry:</b> Transform a friendly Treant into a 5/5 Ancient with <b>Taunt</b>.
    """
    pass


class TTN_930:
    """雪莲幼苗 - Frost Lotus Seedling
    Draw 1 card. Gain 5 Armor. <i>(Blossoms in 3 turns.)</i>
    """
    pass


class TTN_951:
    """自然之拥 - Embrace of Nature
    Draw a <b>Choose One</b> card. <b>Forge:</b> It has both effects combined.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_528:
    """受污染的鞭笞者 - Contaminated Lasher
    [x]<b>Battlecry:</b> If you've cast 5 or more spells this game,  refresh 4 Mana Crystals.@ <i>({0} left!)</i>@ <i>(Ready!)</i>
    """
    pass


class YOG_529:
    """禁忌之果 - Forbidden Fruit
    [x]Spend all your Mana. <b>Choose One -</b> Gain that much Attack this turn; or twice as much Armor.
    """
    pass


# EPIC

class TTN_503:
    """艾欧娜尔的信徒 - Disciple of Eonar
    <b>Battlecry:</b> Your next  <b>Choose One</b> card or power has both effects combined.
    """
    pass


class TTN_926:
    """生长古树 - Ancient of Growth
    [x]<b>Choose One -</b> Summon three 2/2 Treants; or   Transform your Treants into    5/5 Ancients with <b>Taunt</b>.
    """
    pass


# LEGENDARY

class TTN_903:
    """生命的缚誓者艾欧娜尔 - Eonar, the Life-Binder
    [x]<b>Titan</b> After this uses an ability, summon a 5/5 Ancient with <b>Taunt</b>.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_940:
    """自然守护者弗蕾亚 - Freya, Keeper of Nature
    [x]<b>Choose One -</b> Duplicate your hand; or Summon copies of all other friendly minions.
    """
    pass


