"""
TITANS 扩展包 - HUNTER
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_080:
    """神秘动物饲养员 - Fable Stablehand
    [x]<b>Rush</b> <b>Battlecry:</b> If you control a minion with 4 or more Attack, gain +2/+2.
    """
    pass


class TTN_081:
    """颤地觉醒 - Awakening Tremors
    Get three 4/1 Worms. They cost (1).
    """
    pass


class TTN_504:
    """诱骗诡计 - Bait and Switch
    <b>Secret:</b> When a friendly minion is attacked, give it +3/+3.
    """
    pass


class YOG_082:
    """星体射击 - Celestial Shot
    Deal $3 damage. Your next spell has <b>Spell Damage +2</b>.
    """
    pass


# RARE

class TTN_078:
    """神话观测者 - Observer of Myths
    [x]After you summon a minion with more Attack than this, give all friendly minions +1 Attack.
    """
    pass


class TTN_079:
    """虫外有虫 - Always a Bigger Jormungar
    Give a minion +2 Attack and "Excess damage dealt by attacks hits the enemy hero."
    """
    pass


class TTN_302:
    """泰坦锻造陷阱 - Titanforged Traps
    <b>Discover</b> and cast a <b>Secret</b>. <b>Forge:</b> Do it twice.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_505:
    """兽性癫狂 - Bestial Madness
    [x]Give +1 Attack to all minions in your hand, deck, and battlefield.
    """
    pass


class YOG_506:
    """扭曲的霜翼龙 - Twisted Frostwing
    [x]<b>Rush</b> <b>Deathrattle:</b> Summon a Chimaera with stats equal to this minion's Attack.
    """
    pass


# EPIC

class TTN_087:
    """吸附寄生体 - Absorbent Parasite
    <b>Magnetic</b>, <b>Rush</b> Can <b>Magnetize</b> to Mechs and Beasts.
    """
    pass


class TTN_088:
    """牵星短弓 - Starstrung Bow
    [x]Costs (1) less for each  friendly <b>Secret</b> that has   triggered this game.
    """
    pass


# LEGENDARY

class TTN_092:
    """复仇者阿格拉玛 - Aggramar, the Avenger
    <b>Titan</b> <b>Battlecry:</b> Equip a 3/3 Taeshalach.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_752:
    """巨人之父霍迪尔 - Hodir, Father of Giants
    <b>Battlecry:</b> Set the stats of the next three minions you play to 8/8.
    """
    pass


