"""
TITANS 扩展包 - MAGE
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_077:
    """酷冰机器人 - Chill-o-matic
    <b>Magnetic</b> <b>Freeze</b> any character damaged by this minion.
    """
    pass


class TTN_095:
    """流水档案管理员 - Aqua Archivist
    [x]<b>Battlecry:</b> The next  Elemental you play costs (2) less.
    """
    pass


class TTN_477:
    """熔火符文 - Molten Rune
    Deal $3 damage. Get a random spell. <b>Forge:</b> This casts twice.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_519:
    """腐化残渣 - Tainted Remnant
    [x]<b>Battlecry:</b> If you played an Elemental last turn, deal 7 damage randomly split between all enemies.
    """
    pass


# RARE

class TTN_475:
    """破链角斗士 - Unchained Gladiator
    [x]<b>Battlecry:</b> Draw a card. Repeat for each Elemental you played last turn.@ <i>(@)</i>
    """
    pass


class TTN_476:
    """魔法新发现 - Discovery of Magic
    <b>Discover</b> a spell from a spell school you haven't cast this game <i>(from any class)</i>.
    """
    pass


class TTN_478:
    """求知造物 - Inquisitive Creation
    [x]<b>Battlecry:</b> Deal 1 damage to all enemy minions. <i>(Improved by each spell school you've cast this game!)</i>
    """
    pass


class YOG_507:
    """虚空经文 - Void Scripture
    <b>Discover</b> a spell. If you have enough Mana to play it, cast a copy of it at a random enemy.
    """
    pass


class YOG_518:
    """多事的仆从 - Meddlesome Servant
    <b>Battlecry:</b> If you've cast 5 or more spells this game, draw 2 cards.@ <i>({0} left!)</i>@ <i>(Ready!)</i>
    """
    pass


# EPIC

class TTN_085:
    """诺甘农的智慧 - Wisdom of Norgannon
    Draw 2 cards. Costs (1) less for each different spell school you've cast this game.
    """
    pass


class TTN_480:
    """元素激励 - Elemental Inspiration
    [x]For each spell school you have cast this game, summon a 4/5 Vortex with a random <b>Bonus Effect</b>.@ <i>(@)</i>
    """
    pass


# LEGENDARY

class TTN_071:
    """西芙 - Sif
    <b>Spell Damage +1</b> <i>(Improved by each spell school you've cast this game!)</i>
    """
    pass


class TTN_075:
    """诺甘农 - Norgannon
    <b>Titan</b> After this uses an ability, double the power of the other abilities.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


