"""
TITANS 扩展包 - 中立 - RARE
Generated by generate_titans_cards.py
"""
from ..utils import *


class TTN_713:
    """生气的冥狱之犬 - Angry Helhound
    <b>Rush</b> Has +4 Attack on your turn.
    """
    pass


class TTN_714:
    """符文供能魔像 - Runefueled Golem
    <b>Battlecry:</b> <b>Discover</b> a weapon from any class.
    """
    pass


class TTN_718:
    """星光雏龙 - Starlight Whelp
    <b>Battlecry:</b> Get a random card from your starting hand.
    """
    pass


class TTN_741:
    """伪装的克熙尔 - Disguised K'thir
    Each turn this is in your hand, transform into a random card in your opponent's deck.
    """
    pass


class TTN_742:
    """星空投影师 - Celestial Projectionist
    [x]<b>Battlecry:</b> Choose a friendly minion. Add a <b>Temporary</b> copy of it to your hand.
    """
    pass


class YOG_411:
    """越狱者 - Prison Breaker
    [x]<b>Battlecry:</b> If you've cast 5 or more spells this game, deal 2 damage to all enemies. @ <i>({0} left!)</i>@ <i>(Ready!)</i>
    """
    pass


