"""
TITANS 扩展包 - 中立 - EPIC
Generated by generate_titans_cards.py
"""
from ..utils import *


class TTN_083:
    """霍迪尔之子 - Son of Hodir
    <b>Battlecry:</b> Shuffle four 8/8 Giants into your deck that are summoned when drawn.
    """
    pass


class TTN_724:
    """风暴巨人 - Storm Giant
    <b>Taunt</b> <b>Forge:</b> Costs (2) less. Can be <b>Forged</b> endlessly.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_734:
    """机甲跳蛙 - Mecha-Leaper
    <b>Magnetic</b> <b>Deathrattle:</b> Give a friendly Mech +2/+2 and this <b>Deathrattle</b>.
    """
    pass


class TTN_859:
    """命运切分者 - Fate Splitter
    <b>Deathrattle:</b> Get a copy of the last card your opponent played.
    """
    pass


class TTN_924:
    """锋鳞 - Razorscale
    Cards can't cost less than (2).
    """
    pass


class YOG_515:
    """混沌之眼 - Eye of Chaos
    <b>Battlecry:</b> Get two 1/1 Chaotic Tendrils.
    """
    pass


