"""
TITANS 扩展包 - 中立 - COMMON
Generated by generate_titans_cards.py
"""
from ..utils import *


class TTN_039:
    """太阳看护者 - Watcher of the Sun
    <b>Battlecry:</b> Get a random Holy spell. <b>Forge:</b> Also restore 6 Health to your hero.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_042:
    """独眼突击者 - Cyclopian Crusher
    <b>Rush</b> <b>Forge:</b> Gain +3/+2.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_076:
    """机械侏儒向导 - Mechagnome Guide
    <b>Battlecry:</b> <b>Discover</b> a spell. <b>Forge:</b> It costs (3) less.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_458:
    """XB-488清理机器人 - XB-488 Disposalbot
    <b>Battlecry:</b> Deal 5 damage randomly split among all enemy minions. <b>Forge:</b> Gain <b>Lifesteal</b>.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_479:
    """烈焰亡魂 - Flame Revenant
    [x]After you summon an  Elemental, give it +1/+1.
    """
    pass


class TTN_700:
    """羁押装置 - Containment Unit
    [x]<b>Magnetic</b> <b>Deathrattle:</b> Summon a random 8-Cost minion.
    """
    pass


class TTN_710:
    """远古图腾 - Ancient Totem
    
    """
    pass


class TTN_711:
    """萨隆邪铁托维尔 - Saronite Tol'vir
    [x]<b>Taunt</b> Whenever this is attacked, draw a card.
    """
    pass


class TTN_712:
    """锐目搜寻者 - Sharp-Eyed Seeker
    <b>Battlecry:</b> If there is a card in your deck that didn't start there, draw it.
    """
    pass


class TTN_715:
    """迷时始祖幼龙 - Time-Lost Protodrake
    [x]<b>Taunt</b> When you draw this, add a random Dragon to your hand.
    """
    pass


class TTN_723:
    """地铁司机 - Tram Operator
    <b>Battlecry:</b> Draw a Mech. The next Mech you play costs (2) less.
    """
    pass


class TTN_729:
    """岩熔冶锻师 - Melted Maker
    After you <b>Forge</b> a card, get a copy of it.
    """
    pass


class TTN_731:
    """粗心的机械师 - Careless Mechanist
    After you draw your second card in a turn, destroy this.
    """
    pass


class TTN_732:
    """发明机器人 - Invent-o-matic
    Whenever you <b>Magnetize</b> a minion, give it +1/+1.
    """
    pass


class TTN_733:
    """铁血座狼 - Relentless Worg
    <b>Rush</b> After this attacks and kills a minion, restore this to full Health.
    """
    pass


class TTN_754:
    """饥饿的海怪 - Ravenous Kraken
    <b>Battlecry:</b> Destroy a friendly minion. <b>Deathrattle:</b> Summon a copy of it.
    """
    pass


class TTN_812:
    """得胜的维库人 - Victorious Vrykul
    After this attacks, get a 2/3 Val'kyr that costs (1).
    """
    pass


class TTN_832:
    """流亡穴居人 - Trogg Exile
    <b>Rush</b> <b>Battlecry:</b> Deal 4 damage to your hero.
    """
    pass


class TTN_860:
    """无人机拆解器 - Drone Deconstructor
    [x]<b>Battlecry:</b> Get a 1/1 <b>Magnetic</b> Sparkbot with a random <b>Bonus Effect</b>.
    """
    pass


class TTN_931:
    """威严的阿努比萨斯 - Imposing Anubisath
    <b>Taunt</b> Can't attack.
    """
    pass


class YOG_514:
    """混乱触须 - Chaotic Tendril
    <b>Battlecry:</b> Cast a random 1-Cost spell. Improve your future Chaotic Tendrils.
    """
    pass


