"""
TITANS 扩展包 - 中立 - LEGENDARY
Generated by generate_titans_cards.py
"""
from ..utils import *


class TTN_090:
    """尤格-萨隆的监狱 - Prison of Yogg-Saron
    [x]Choose a character. Cast 4 random spells <i>(targeting it if possible)</i>.
    """
    pass


class TTN_330:
    """科隆加恩 - Kologarn
    [x]<b>Rush</b>. Whenever this attacks a minion, put it in your hand. <b>Deathrattle:</b> Move any in your   hand to your opponent's.
    """
    pass


class TTN_716:
    """烈焰猛兽 - Flame Behemoth
    <b>Battlecry:</b> Get two random <b>Magnetic</b> Mechs. They cost (2) less.
    """
    pass


class TTN_717:
    """观察者奥尔加隆 - Algalon the Observer
    <b>Battlecry:</b> Replace your Hero Power with Algalon's Vision.
    """
    pass


class TTN_751:
    """永恒之火伊格尼斯 - Ignis, the Eternal Flame
    <b>Battlecry:</b> If you've <b>Forged</b> a card this game, craft a custom weapon.
    """
    pass


class YOG_516:
    """脱困古神尤格-萨隆 - Yogg-Saron, Unleashed
    [x]<b>Titan</b> After this uses an ability, cast two random spells.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class YOG_530:
    """暮光头领古加尔 - Cho'gall, Twilight Chieftain
    [x]<b>Taunt</b>, <b>Lifesteal</b> <b>Start of Game:</b> 50% chance to corrupt the game with a random anomaly.
    """
    pass


