"""
TITANS 扩展包 - PALADIN
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_852:
    """崇高的迷你机 - Noble Minibot
    <b>Magnetic</b> After this attacks, give a random minion in your hand +1/+1.
    """
    pass


class TTN_854:
    """发明家的光环 - Inventor's Aura
    Your Mechs cost (1) less. Lasts 2 turns.
    """
    pass


class TTN_907:
    """星界翔龙 - Astral Serpent
    At the end of your turn, if this didn't attack, draw 2 cards.
    """
    pass


class YOG_525:
    """健身肌器人 - Muscle-o-Tron
    [x]<b>Battlecry:</b> Give all minions in your hand +1/+1. <b>Forge:</b> +2/+2 instead.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


# RARE

class TTN_855t:
    """提尔之涕 - Tyr's Tears
    [x]Resurrect 3 different  minions from your class. Set their stats to 2/2. <b>Forge:</b> Resurrect another.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_900:
    """石心之王 - Stoneheart King
    [x]<b>Deathrattle:</b> Summon a 2/2 Earthen that gains +2/+2 for each other Earthen you've summoned this game.
    """
    pass


class TTN_906:
    """修理机器人X-21 - X-21 Repairbot
    <b>Deathrattle:</b> Return any Mechs <b>Magnetized</b> to this to your hand.
    """
    pass


class YOG_509:
    """守护者的力量 - Keeper's Strength
    Give a friendly minion +2/+2. Deal its Attack damage to all other minions.
    """
    pass


class YOG_510:
    """报警安保机器人 - Alarmed Securitybot
    [x]<b>Deathrattle:</b> Draw another minion. Set its Attack, Health, and Cost to 5.
    """
    pass


# EPIC

class TTN_853:
    """审判恶徒 - Judge Unworthy
    Set an enemy minion's Health to 1, then deal $1 damage to all enemies.
    """
    pass


class TTN_856:
    """阿米图斯的信徒 - Disciple of Amitus
    [x]At the end of your turn, summon a 2/2 Earthen that gains +2/+2 for each other Earthen you've summoned this game.
    """
    pass


# LEGENDARY

class TTN_857:
    """提尔 - Tyr
    <b>Battlecry:</b> Resurrect a 2, 3, and 4-Attack minion from your class.
    """
    pass


class TTN_858:
    """维和者阿米图斯 - Amitus, the Peacekeeper
    <b>Titan</b> <b>Taunt</b>. Your minions can't take more than 2 damage at a time.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


