"""
TITANS 扩展包 - PRIEST
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_482:
    """星辰的学生 - Student of the Stars
    <b>Deathrattle:</b> Shuffle a copy of this into your deck with permanent +3/+3.
    """
    pass


class TTN_483:
    """平心静气 - Serenity
    Give all enemy minions -2 Attack. Destroy any with 0 Attack.
    """
    pass


class TTN_745:
    """众神之父的恩赐 - Grace of the Highfather
    Restore #8 Health. <b>Discover</b> a card that costs the amount <b>Overhealed</b>.
    """
    pass


class YOG_508:
    """暮光洪流 - Twilight Torrent
    Choose a character. If it's friendly, restore #6 Health. If it's an enemy, deal $3 damage.
    """
    pass


# RARE

class TTN_401:
    """星界自动机 - Astral Automaton
    [x]Has +1/+1 for each other Astral Automaton you've summoned this game.
    """
    pass


class TTN_430:
    """造物协议 - Creation Protocol
    <b>Discover</b> a copy of a minion in your deck. <b>Forge:</b> Get another copy.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_484:
    """伪信徒 - False Disciple
    <b>Battlecry:</b> <b>Discover</b> a <b>Legendary</b> Priest minion from the past.
    """
    pass


class YOG_300:
    """影触克瓦迪尔 - Shadowtouched Kvaldir
    <b>Battlecry:</b> Your next healing effect deals damage instead.
    """
    pass


# EPIC

class TTN_441:
    """无象星座 - Shapeless Constellation
    <b>Battlecry:</b> Transform into an 8/8 copy of a random minion in your hand.
    """
    pass


class TTN_485:
    """星辰排列 - The Stars Align
    Transform minions in your hand into ones that cost (3) more. <i>(They keep their original Cost.)</i>
    """
    pass


# LEGENDARY

class TTN_429:
    """阿曼苏尔 - Aman'Thul
    [x]<b>Titan</b> After this uses an ability, <b>Discover</b> any <b>Legendary</b>  minion from any class.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_481:
    """莱登 - Ra-den
    [x]<b>Taunt</b>. <b>Deathrattle:</b> Summon each other minion you've played this game that did not start in your deck.
    """
    pass


class YOG_520:
    """燃魂者瓦利亚 - Soulburner Varia
    [x]After a friendly Undead dies, deal 2 damage to the enemy hero and get a random Shadow Priest spell.
    """
    pass


