"""
TITANS 扩展包 - PRIEST
Generated by generate_titans_cards.py
"""
from ..utils import *
from ... import enums
from ...dsl.lazynum import EventArgument


# COMMON

class TTN_482:
    """星辰的学生 - Student of the Stars
    <b>亡语：</b>将本随从的一张永久具有+3/+3的复制洗入你的牌库。
    """
    tags = {
        GameTag.ATK: 4,
        GameTag.HEALTH: 3,
        GameTag.COST: 3,
    }

    def deathrattle(self):
        # 创建一张本随从的复制，并给予永久+3/+3增益
        copy_card = self.controller.card(self.id, self.controller)
        copy_card.tags[GameTag.ATK] += 3
        copy_card.tags[GameTag.HEALTH] += 3
        yield Shuffle(CONTROLLER, copy_card)


class TTN_483:
    """平心静气 - Serenity
    使所有敌方随从获得-2攻击力。消灭具有0点攻击力的敌方随从。
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 4,
        GameTag.SPELL_SCHOOL: SpellSchool.HOLY,
    }

    def play(self):
        # 使所有敌方随从获得-2攻击力
        yield Buff(ENEMY_MINIONS, "TTN_483e")
        # 消灭具有0点攻击力的敌方随从
        yield Destroy(ENEMY_MINIONS + (ATK == 0))


class TTN_483e:
    """平心静气附魔"""
    tags = {
        GameTag.ATK: -2,
        GameTag.CARDTYPE: CardType.ENCHANTMENT,
    }


class TTN_745:
    """众神之父的恩赐 - Grace of the Highfather
    恢复#8点生命值。<b>发现</b>一张法力值消耗等同于<b>过量治疗</b>量的牌。
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 3,
        GameTag.SPELL_SCHOOL: SpellSchool.HOLY,
    }

    requirements = {
        PlayReq.REQ_TARGET_TO_PLAY: 0,
    }

    def play(self):
        target = self.target
        # 记录治疗前的生命值
        damage_before = target.damage

        # 恢复8点生命值
        yield Heal(target, 8)

        # 计算实际过量治疗量：治疗量 - 实际恢复的生命值
        damage_after = target.damage
        actual_healing = damage_before - damage_after
        overheal_amount = 8 - actual_healing

        # 如果有过量治疗，发现一张对应费用的牌
        if overheal_amount > 0:
            yield Discover(CONTROLLER, RandomCollectible(cost=overheal_amount))


class YOG_508:
    """暮光洪流 - Twilight Torrent
    选择一个角色。如果是友方角色，为其恢复#6点生命值；如果是敌方角色，对其造成$3点伤害。
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 2,
        GameTag.SPELL_SCHOOL: SpellSchool.SHADOW,
    }

    requirements = {
        PlayReq.REQ_TARGET_TO_PLAY: 0,
    }

    def play(self):
        target = self.target
        # 判断是友方还是敌方角色
        if target.controller == self.controller:
            # 友方角色：恢复6点生命值
            yield Heal(target, 6)
        else:
            # 敌方角色：造成3点伤害
            yield Hit(target, 3)


# RARE

class TTN_401:
    """星界自动机 - Astral Automaton
    在本局对战中，你每召唤过一个其他星界自动机，便拥有+1/+1。
    """
    tags = {
        GameTag.ATK: 1,
        GameTag.HEALTH: 2,
        GameTag.COST: 1,
        GameTag.CARDRACE: Race.MECHANICAL,
    }

    # 每召唤一个其他星界自动机时，获得+1/+1
    events = Summon(CONTROLLER, MINION + (ID == "TTN_401") - SELF).on(
        Buff(SELF, "TTN_401e")
    )


class TTN_401e:
    """星界自动机增益"""
    tags = {
        GameTag.ATK: 1,
        GameTag.HEALTH: 1,
        GameTag.CARDTYPE: CardType.ENCHANTMENT,
    }


class TTN_430:
    """造物协议 - Creation Protocol
    从你的牌库中<b>发现</b>一张随从牌的复制。<b>锻造：</b>再获取一张复制。
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 2,
        GameTag.SPELL_SCHOOL: SpellSchool.HOLY,
    }

    play = Discover(CONTROLLER, RANDOM(FRIENDLY_DECK + MINION)).then(
        Give(CONTROLLER, Copy(Discover.CARD))
    )


class TTN_430t:
    """造物协议 - Creation Protocol (Forged)
    从你的牌库中<b>发现</b>一张随从牌的复制。再获取一张复制。
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 2,
        GameTag.SPELL_SCHOOL: SpellSchool.HOLY,
    }

    def play(self):
        # 发现一张随从牌，获取两张复制
        discovered = yield Discover(CONTROLLER, RANDOM(FRIENDLY_DECK + MINION))
        if discovered:
            yield Give(CONTROLLER, Copy(discovered[0]))
            yield Give(CONTROLLER, Copy(discovered[0]))


class TTN_484:
    """伪信徒 - False Disciple
    <b>战吼：</b><b>发现</b>一张来自过去的牧师 <b>传说</b>随从牌。
    """
    tags = {
        GameTag.ATK: 2,
        GameTag.HEALTH: 2,
        GameTag.COST: 2,
    }

    # 发现一张牧师传说随从牌（来自过去 = Wild卡池）
    play = Discover(CONTROLLER, RandomLegendaryMinion(
        card_class=CardClass.PRIEST,
        is_standard=False
    ))


class YOG_300:
    """影触克瓦迪尔 - Shadowtouched Kvaldir
    <b>战吼：</b>你的下一次治疗效果转而造成等量的伤害。
    """
    tags = {
        GameTag.ATK: 1,
        GameTag.HEALTH: 3,
        GameTag.COST: 1,
        GameTag.CARDRACE: Race.UNDEAD,
    }

    play = Buff(CONTROLLER, "YOG_300e")


class YOG_300e:
    """影触 - Shadowtouched
    你的下一次治疗效果转而造成等量的伤害。
    """
    tags = {
        GameTag.CARDTYPE: CardType.ENCHANTMENT,
        GameTag.EMBRACE_THE_SHADOW: True,
    }

    # 使用核心已有的 EMBRACE_THE_SHADOW 机制
    # 核心在 actions.py:2035 已实现：if source.controller.healing_as_damage
    # 需要在治疗后移除此 buff（仅生效一次）
    events = Heal(CONTROLLER).after(Destroy(SELF))


# EPIC

class TTN_441:
    """无象星座 - Shapeless Constellation
    <b>战吼：</b>随机变形成为你手牌中一个随从的8/8的复制。
    """
    tags = {
        GameTag.ATK: 8,
        GameTag.HEALTH: 8,
        GameTag.COST: 8,
    }

    def play(self):
        # 随机选择手牌中的一个随从
        target = yield RANDOM(FRIENDLY_HAND + MINION)
        if target:
            # 变形为该随从的复制，然后设置为8/8
            yield Morph(SELF, Copy(target[0]))
            yield SetTags(SELF, {GameTag.ATK: 8, GameTag.HEALTH: 8})


class TTN_485:
    """星辰排列 - The Stars Align
    将你手牌中的随从牌变形成为法力值消耗增加（3）点的随从牌。<i>（保留其原始法力值消耗。）</i>
    """
    tags = {
        GameTag.CARDTYPE: CardType.SPELL,
        GameTag.COST: 3,
        GameTag.SPELL_SCHOOL: SpellSchool.ARCANE,
    }

    def play(self):
        # 将手牌中的所有随从牌变形为费用+3的随从
        for minion in self.controller.hand.filter(type=CardType.MINION):
            original_cost = minion.cost
            # 变形为费用+3的随从
            yield Morph(minion, RandomMinion(cost=original_cost + 3))


# LEGENDARY

class TTN_429:
    """阿曼苏尔 - Aman'Thul
    <b>泰坦</b> 在本随从使用一个技能后，<b>发现</b>任意职业的<b>传说</b>随从牌。
    """
    tags = {
        GameTag.ATK: 3,
        GameTag.HEALTH: 10,
        GameTag.COST: 7,
        GameTag.LEGENDARY: True,
        GameTag.TITAN: True,
        enums.TITAN_ABILITY_COUNT: 3,  # 泰坦技能次数
    }

    def _discover_legendary(self):
        """使用技能后发现传说随从"""
        yield Discover(CONTROLLER, RandomLegendaryMinion())

    # 技能1需要目标
    titan_ability_1_requirements = {
        PlayReq.REQ_TARGET_TO_PLAY: 0,
        PlayReq.REQ_MINION_TARGET: 0,
    }

    def titan_ability_1(self):
        """时光倒流 - Rewind Time
        使一个随从回到你的手牌。
        """
        yield Bounce(TARGET)
        yield self._discover_legendary()

    def titan_ability_2(self):
        """时光加速 - Accelerate Time
        抽两张牌。
        """
        yield Draw(CONTROLLER, 2)
        yield self._discover_legendary()

    def titan_ability_3(self):
        """时光停滞 - Freeze Time
        冻结所有敌方随从。
        """
        yield Freeze(ENEMY_MINIONS)
        yield self._discover_legendary()


class TTN_481:
    """莱登 - Ra-den
    <b>嘲讽</b>。<b>亡语：</b>召唤你在本局对战中使用过的你套牌之外的每个其他随从。
    """
    tags = {
        GameTag.ATK: 5,
        GameTag.HEALTH: 5,
        GameTag.COST: 6,
        GameTag.LEGENDARY: True,
        GameTag.TAUNT: True,
    }

    def deathrattle(self):
        # 召唤本局对战中使用过的套牌外的随从
        # 使用核心已有的 minions_played_from_outside_deck 机制
        # 参考：RLK_803（大法师罗曼斯）使用 spells_cast_not_from_deck
        for minion_id in self.controller.minions_played_from_outside_deck:
            if minion_id != self.id:  # 排除自己
                yield Summon(CONTROLLER, minion_id)


class YOG_520:
    """燃魂者瓦利亚 - Soulburner Varia
    在一个友方亡灵死亡后，对敌方英雄造成2点伤害，并随机获取一张牧师暗影法术牌。
    """
    tags = {
        GameTag.ATK: 1,
        GameTag.HEALTH: 5,
        GameTag.COST: 3,
        GameTag.LEGENDARY: True,
        GameTag.CARDRACE: Race.UNDEAD,
    }

    # 友方亡灵死亡时触发
    events = Death(FRIENDLY + UNDEAD).on(
        Hit(ENEMY_HERO, 2),
        Give(CONTROLLER, RandomSpell(
            card_class=CardClass.PRIEST,
            spell_school=SpellSchool.SHADOW
        ))
    )

