"""
TITANS 扩展包 - ROGUE
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_719:
    """废料回收 - From the Scrapheap
    Get three 1/1 <b>Magnetic</b> Sparkbots with random <b>Bonus Effects</b>.
    """
    pass


class TTN_921:
    """铜尾刺探鼠 - Coppertail Snoop
    [x]<b>Magnetic</b> Whenever this attacks, get a Coin.
    """
    pass


class TTN_923:
    """SP-3Y3-D3R蛛型机 - SP-3Y3-D3R
    <b>Magnetic</b> <b>Stealth</b> for 1 turn.
    """
    pass


class YOG_526:
    """触须缠握 - Tentacle Grip
    Deal $3 damage. <b>Combo:</b> Get a 1/1 Chaotic Tendril.
    """
    pass


class YOG_527:
    """迷你灭世者 - Tiny Worldbreaker
    <b>Battlecry:</b> If you control another Mech, deal 4 damage.
    """
    pass


# RARE

class TTN_728:
    """整备站 - Pit Stop
    <b>Discover</b> a Mech from your deck. Give it +2/+1.
    """
    pass


class TTN_922:
    """换挡漂移 - Gear Shift
    Shuffle the two left-most cards in your hand into your deck. Draw 3 cards.
    """
    pass


class TTN_925:
    """卡亚矿石造物 - Kaja'mite Creation
    <b>Battlecry:</b> <b>Discover</b> a spell from another class that costs (3) or less.
    """
    pass


class YOG_410:
    """汇编阵线 - Assembly Line
    <b>Discover</b> a Mech from another class.
    """
    pass


# EPIC

class TTN_726:
    """焦油飞溅 - Tar Slick
    Minions take double damage this turn. Deal $1 damage.
    """
    pass


class TTN_730:
    """实验室构筑机 - Lab Constructor
    [x]At the end of your turn, summon a copy of this. <b>Forge:</b> Gain <b>Magnetic</b>.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


# LEGENDARY

class TTN_721:
    """终极V-07-TR-0N - V-07-TR-0N Prime
    [x]<b>T1T4N</b> This minion's abilities repeat on another random friendly minion.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_920:
    """天才米米尔隆 - Mimiron, the Mastermind
    [x]After you play a Mech, get a random one of Mimiron's Gadgets.
    """
    pass


