"""
TITANS 扩展包 - SHAMAN
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_722:
    """潮流逆转 - Turn the Tides
    [x]Give your hero +3 Attack this turn. Summon a 3/3 Elemental with <b>Rush</b>. <b>Overload:</b> (1)
    """
    pass


class TTN_831:
    """雷电崩鸣 - Crash of Thunder
    Deal $3 damage to all enemies. Costs (1) less for each Nature spell you've cast this turn.
    """
    pass


class TTN_833:
    """高戈奈斯的信徒 - Disciple of Golganneth
    [x]At the end of your turn, reduce the Cost of a random <b>Overload</b> card in your hand by (1).
    """
    pass


class YOG_523:
    """被寄生的看守者 - Infested Watcher
    [x]<b>Taunt</b> <b>Deathrattle:</b> Get two 1/1 Chaotic Tendrils.
    """
    pass


class YOG_524:
    """雷电跳蛙 - Shock Hopper
    [x]<b>Battlecry:</b> Get a random <b>Overload</b> card.
    """
    pass


# RARE

class TTN_317:
    """闪电反射 - Lightning Reflexes
    [x]<b>Discover</b> a Nature spell. If you play it this turn, <b>Discover</b> another.
    """
    pass


class TTN_725:
    """雷霆之锤 - Tempest Hammer
    After your hero attacks, deal 3 damage to the lowest Health enemy.
    """
    pass


class TTN_727:
    """托林尼尔幼龙 - Thorignir Drake
    [x]<b>Rush</b> Whenever this attacks, summon two 3/1 Whelps to attack the target first.
    """
    pass


class YOG_522:
    """电流导联 - Conductivity
    The next spell you cast this turn also targets adjacent minions.
    """
    pass


# EPIC

class TTN_801:
    """风暴勇士 - Champion of Storms
    After you cast a Nature spell, summon a 4/2 Elemental. <b>Forge:</b> With <b>Rush</b>.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class TTN_830:
    """须臾闪电 - Flash of Lightning
    Draw a card. Next turn, your Nature spells cost (1) less.
    """
    pass


# LEGENDARY

class TTN_800:
    """雷霆之神高戈奈斯 - Golganneth, the Thunderer
    <b>Titan</b> Your first spell each turn costs (3) less.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_835:
    """风暴之王托里姆 - Thorim, Stormlord
    [x]<b>Battlecry:</b> Unlock your <b>Overloaded</b> Mana Crystals. Draw that many cards.
    """
    pass


