"""
TITANS 扩展包 - WARLOCK
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_456:
    """蔽刺触手 - Thornveil Tentacle
    [x]<b>Lifesteal</b> <b>Battlecry:</b> Deal 2 damage to a random enemy minion.
    """
    pass


class TTN_463:
    """飞翼焊装 - Wing Welding
    [x]Discard your highest Cost card. Deal damage equal to its Cost to all minions.
    """
    pass


class TTN_486:
    """魔化形态 - Monstrous Form
    Give a friendly minion +3/+3 until your next turn.
    """
    pass


class YOG_517:
    """触须宠溺者 - Tentacle Tender
    At the end of your turn, get a 1/1 Chaotic Tendril.
    """
    pass


# RARE

class TTN_460:
    """致命诛灭 - Mortal Eradication
    [x]Deal $5 damage randomly split among all enemy minions. Restore #2 Health to your hero for each killed.
    """
    pass


class TTN_465:
    """意志熔炉 - Forge of Wills
    Choose a friendly minion. Summon a Giant with its stats and <b>Rush</b>.
    """
    pass


class TTN_490:
    """萨格拉斯的信徒 - Disciple of Sargeras
    <b>Battlecry:</b> Discard a spell to summon two 3/2 Imps. <b>Forge:</b> Give them +2 Health and <b>Taunt</b>.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_301:
    """狂乱侵蚀 - Encroaching Insanity
    Both players take Fatigue damage, twice.
    """
    pass


class YOG_503:
    """血肉诅咒 - Curse of Flesh
    Enemy minions cost Health instead of Mana next turn.
    """
    pass


# EPIC

class TTN_462:
    """被禁锢的恐魔 - Imprisoned Horror
    [x]Costs (1) less for each damage you've taken on your turns this game.
    """
    pass


class TTN_932:
    """混乱吞噬 - Chaotic Consumption
    Destroy a friendly minion to destroy an enemy minion.
    """
    pass


# LEGENDARY

class TTN_487:
    """洛肯，尤格-萨隆的看守 - Loken, Jailer of Yogg-Saron
    [x]<b>Battlecry:</b> <b>Discover</b> a minion from your deck. Summon a Tentacle with its stats and <b>Taunt</b>.
    """
    pass


class TTN_960:
    """灭世泰坦萨格拉斯 - Sargeras, the Destroyer
    [x]<b>Titan</b> <b>Battlecry:</b> Open a portal that summons two 3/2 Imps each turn.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


