"""
TITANS 扩展包 - WARRIOR
Generated by generate_titans_cards.py
"""
from ..utils import *


# COMMON

class TTN_467:
    """匠人之锤 - Craftsman's Hammer
    Whenever your hero attacks, gain 4 Armor.
    """
    pass


class TTN_468:
    """蒸汽守卫 - Steam Guardian
    [x]<b>Battlecry:</b> Draw a spell. Reduce the Cost of a Fire spell in your hand by (1).
    """
    pass


class TTN_753:
    """鼓动火焰 - Bellowing Flames
    Deal $5 damage to a minion. <b>Forge:</b> Then deal $5 damage split among all enemy minions.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


class YOG_502:
    """清理污染 - Sanitize
    [x]Deal damage equal to your Armor to all minions. <b>Forge:</b> Gain 3 Armor first.
    """
    # TODO: 实现 Forge 效果
    forge = None  # Forge effect placeholder
    pass


# RARE

class TTN_466:
    """米诺陶牛头人 - Minotauren
    [x]<b>Rush</b> Whenever this minion deals damage, gain that much Armor.
    """
    pass


class TTN_469:
    """岩肤护甲商 - Stoneskin Armorer
    <b>Battlecry:</b> If your Armor changed this turn, draw 2 cards.
    """
    pass


class TTN_803:
    """熔铸 - Smelt
    [x]Give a random minion in your hand +3/+3. Lose 3 Armor to do it again.
    """
    pass


class YOG_501:
    """历战无面者 - Battleworn Faceless
    <b>Battlecry:</b> Transform into a copy of a damaged minion.
    """
    pass


# EPIC

class TTN_470:
    """火焰试炼 - Trial by Fire
    [x]Summon five 1/1 Val'kyr with <b>Rush</b>. When one dies, give the others +1/+1.
    """
    pass


class TTN_471:
    """愤怒焚炉 - Furious Furnace
    [x]<b>Magnetic</b> Also damages minions next to whomever this attacks.
    """
    pass


# LEGENDARY

class TTN_415:
    """卡兹格罗斯 - Khaz'goroth
    [x]<b>Titan</b> After this uses an ability, gain <b>Immune</b> this turn and attack a random enemy minion.
    """
    # TODO: 实现 Titan 技能
    # Titan 卡牌有 3 个特殊技能
    pass


class TTN_811:
    """首席管理官奥丁 - Odyn, Prime Designate
    [x]<b>Battlecry:</b> For the rest of the game, after your hero gains Armor, they gain that much Attack for that turn.
    """
    pass


class YOG_500:
    """维扎克斯将军 - General Vezax
    [x]<b>Rush</b> <b>Battlecry:</b> Gain 4 Armor. <b>Deathrattle:</b> Lose 4 Armor to resummon this.
    """
    pass


