from enum import IntEnum


##
# Internal fireplace tags

KILLED_THIS_TURN = -10
ALWAYS_WINS_BRAWLS = -11
CANT_OVERLOAD = -12
EXTRA_BATTLECRIES = -13
DISCARDED = -14
MURLOCS_COST_HEALTH = -15
CAST_ON_FRIENDLY_MINIONS = -16
UNLIMITED_ATTACKS = -17
ELEMENTAL_PLAYED_LAST_TURN = -18
HEROPOWER_DISABLED = -19
EXTRA_END_TURN_EFFECT = -20
PASSIVE_HERO_POWER = -21
KEEP_BUFF = -22
DAMAGED_THIS_TURN = -23
MINION_EXTRA_COMBOS = -24
MINION_EXTRA_BATTLECRIES = -25
EXTRA_TRIGGER_SECRET = -26
CAST_ON_FRIENDLY_CHARACTERS = -27
CUSTOM_CARDTEXT = -28
ACTIVATIONS_THIS_TURN = -29
LIFESTEAL_DAMAGES_ENEMY = -30
TRADEABLE_ACTIVE = -31  # 卡牌是否可以被交易
TRADED_THIS_TURN = -32  # 本回合是否已交易过此卡
INFUSE_COUNTER = -33  # Infuse 充能计数器
INFUSE_THRESHOLD = -34  # Infuse 需要的充能数量
LOCATION_COOLDOWN = -35  # 地标是否处于冷却状态
LOCATION_ACTIVATIONS_THIS_TURN = -36  # 本回合激活次数
FORGE_ACTIVE = -37  # 卡牌是否可以被锻造
FORGED = -38  # 卡牌是否已被锻造
TITAN_ABILITY_USED = -39  # 泰坦已使用的技能次数
TITAN_ABILITY_COUNT = -40  # 泰坦总共有多少个技能（通常是3个）
TITAN_ABILITY_USED_1 = -101 # 泰坦技能1是否已使用
TITAN_ABILITY_USED_2 = -102 # 泰坦技能2是否已使用
TITAN_ABILITY_USED_3 = -103 # 泰坦技能3是否已使用
SPELL_DOUBLE_CAST = -41  # 下一个法术施放两次（Solar Eclipse等）
NUM_SECRETS_REVEALED = -42  # 本局对战中触发的友方奥秘次数
HONORABLE_KILL = -79  # 荣誉消灭效果（奥特兰克扩展包）
ALWAYS_WINS_BRAWLS = -80  # 总是赢得绝命乱斗（决战荒芜之地扩展包）

# Questline（任务线）机制 - 暴风城（2021年8月）
QUESTLINE_STAGE = -43  # 任务线当前阶段（1/2/3）
QUESTLINE_PROGRESS = -44  # 当前阶段的进度

# Ranked Spells（等级法术）机制 - 贫瘠之地（2021年3月）
RANKED_SPELL_NEXT_RANK = -45  # 下一等级的卡牌 ID（字符串）
RANKED_SPELL_THRESHOLD = -46  # 升级所需的法力水晶数量

# Relic（圣物）机制 - 纳斯利亚堡（2022年8月）
RELIC = -47  # 标记卡牌是否为圣物

# 奥秘保护机制 - 纳斯利亚堡（2022年8月）
CANT_BE_REVEALED = -48  # 标记奥秘不能被揭示（MAW_032 无语的证人）

# 复制卡追踪机制 - 纳斯利亚堡（2022年8月）
COPIED_FROM_OPPONENT = -49  # 标记卡牌是从对手复制的（用于牧师主题卡牌）

# 变形免疫机制 - 纳斯利亚堡（2022年8月）
TRANSFORM_IMMUNE = -50  # 标记随从免疫变形（用于瓦丝琪女男爵）

# 最小生命值机制 - 纳斯利亚堡（2022年8月）
MINIMUM_HEALTH = -51  # 限制最小生命值（用于动乱等卡牌）

# 残骸系统 - 巫妖王的进军（2022年12月）
CORPSE_COUNT = -52  # 玩家当前残骸数量（已在 player.corpses 实现）

# 生命值消耗机制 - 贫瘠之地（2021年3月）
HEALTH_COST = -53  # 标记卡牌消耗生命值而非法力值（用于灵魂窃贼等卡牌）

# 下一份药剂减费机制 - 巫妖王的进军（2022年12月）
NEXT_POTION_COST_ZERO = -54  # 标记下一份药剂费用为0（用于食尸鬼炼金师等卡牌）

# 溢出伤害机制 - 泰坦诸神（2023年8月）
EXCESS_DAMAGE_TO_HERO = -55  # 标记随从攻击时溢出伤害命中敌方英雄（用于虫外有虫等卡牌）

# 特殊磁力机制 - 泰坦诸神（2023年8月）
MAGNETIC_TARGET_RACES = -56  # 磁力可吸附的目标种族列表（用于吸附寄生体等特殊磁力卡）

# 随从消耗生命值机制 - 泰坦诸神（2023年8月）
MINIONS_COST_HEALTH = -57  # 标记随从牌消耗生命值而非法力值（用于YOG_503血肉诅咒等卡牌）

# 星舰机制 - 深暗领域（2024年11月）
STARSHIP_PIECE = -58  # 标记随从是星舰组件
STARSHIP_ATTACK = -59  # 星舰累积的攻击力
STARSHIP_HEALTH = -60  # 星舰累积的生命值
STARSHIP_PIECES_COUNT = -61  # 星舰包含的组件数量
STARSHIP_LAUNCHED_THIS_GAME = -62  # 本局对战中是否发射过星舰

# Imbue 机制 - 深入翡翠梦境（2025年3月）
IMBUE = -63  # 标记卡牌具有 Imbue 效果
IMBUE_LEVEL = -64  # 当前 Imbue 等级（0=未激活，1=初始，2+=升级）
IMBUED_HERO_POWER = -65  # 标记英雄技能是否为 Imbued 版本

# Dark Gift 机制 - 深入翡翠梦境（2025年3月）
DARK_GIFT = -66  # 标记随从具有黑暗之赐效果
DARK_GIFT_BONUS = -67  # 存储黑暗之赐的奖励效果ID
DARK_GIFT_SUMMON_COPY = -68  # 标记随从打出时召唤2/2复制
DARK_GIFT_TO_DECK_TOP = -69  # 标记随从需要置于牌库顶

# 变形费用修改机制 - 深入翡翠梦境（2025年3月）
TRANSFORM_COST_MODIFIER = -70  # 标记随从变形时费用修改量（用于胆大的魔荚人）

# Kindred 机制 - 失落之城（2025年7月）
KINDRED = -71  # 标记卡牌具有 Kindred 效果
KINDRED_ACTIVE = -72  # 标记 Kindred 效果是否激活（上回合打出过同类型/学派）

# Map Cards 机制 - 失落之城（2025年7月）
MAP_DISCOVERED_THIS_TURN = -73  # 标记本回合从地图发现的卡牌ID（用于触发二次发现）

# Rewind 机制 - 穿越时间流（2025年11月）
REWIND = -74  # 标记卡牌具有 Rewind 效果
REWIND_COUNT = -75  # 标记卡牌可以 Rewind 的次数
REWIND_AVAILABLE = -76  # 标记卡牌当前是否可以 Rewind

# Fabled 机制 - 穿越时间流（2025年11月）
FABLED = -77  # 标记卡牌为 Fabled 传说卡牌
FABLED_CARDS = -78  # 存储 Fabled 卡牌附带的额外卡牌ID列表

# 自然法术伤害加成 - 贫瘠之地（2021年3月）
NATURE_SPELL_DAMAGE = -81  # 自然法术伤害加成（用于布鲁坎等卡牌）





class SpellType(IntEnum):
    INVALID = 0
    SECRET = 1
    QUEST = 2
    SIDEQUEST = 3
    TRIGGER_EFFECT = 4


class PlayReq(IntEnum):
    """
    The playRequirements attribute contains an array of key: param values
    which determine various requirements which have to be met for the card
    to be played and what it can target.

    Copy from python-hearthstone, that don't maintain this enum.
    see: https://github.com/HearthSim/python-hearthstone/pull/45
    """

    INVALID = -1
    REQ_MINION_TARGET = 1
    REQ_FRIENDLY_TARGET = 2
    REQ_ENEMY_TARGET = 3
    REQ_DAMAGED_TARGET = 4
    REQ_MAX_SECRETS = 5
    REQ_FROZEN_TARGET = 6
    REQ_CHARGE_TARGET = 7
    REQ_TARGET_MAX_ATTACK = 8
    REQ_NONSELF_TARGET = 9
    REQ_TARGET_WITH_RACE = 10
    REQ_TARGET_TO_PLAY = 11
    REQ_NUM_MINION_SLOTS = 12
    REQ_WEAPON_EQUIPPED = 13
    REQ_ENOUGH_MANA = 14
    REQ_YOUR_TURN = 15
    REQ_NONSTEALTH_ENEMY_TARGET = 16
    REQ_HERO_TARGET = 17
    REQ_SECRET_ZONE_CAP = 18
    REQ_MINION_CAP_IF_TARGET_AVAILABLE = 19
    REQ_MINION_CAP = 20
    REQ_TARGET_ATTACKED_THIS_TURN = 21
    REQ_TARGET_IF_AVAILABLE = 22
    REQ_MINIMUM_ENEMY_MINIONS = 23
    REQ_TARGET_FOR_COMBO = 24
    REQ_NOT_EXHAUSTED_ACTIVATE = 25
    REQ_UNIQUE_SECRET_OR_QUEST = 26
    REQ_TARGET_TAUNTER = 27
    REQ_CAN_BE_ATTACKED = 28
    REQ_ACTION_PWR_IS_MASTER_PWR = 29
    REQ_TARGET_MAGNET = 30
    REQ_ATTACK_GREATER_THAN_0 = 31
    REQ_ATTACKER_NOT_FROZEN = 32
    REQ_HERO_OR_MINION_TARGET = 33
    REQ_CAN_BE_TARGETED_BY_SPELLS = 34
    REQ_SUBCARD_IS_PLAYABLE = 35
    REQ_TARGET_FOR_NO_COMBO = 36
    REQ_NOT_MINION_JUST_PLAYED = 37
    REQ_NOT_EXHAUSTED_HERO_POWER = 38
    REQ_CAN_BE_TARGETED_BY_OPPONENTS = 39
    REQ_ATTACKER_CAN_ATTACK = 40
    REQ_TARGET_MIN_ATTACK = 41
    REQ_CAN_BE_TARGETED_BY_HERO_POWERS = 42
    REQ_ENEMY_TARGET_NOT_IMMUNE = 43
    REQ_ALL_BASIC_TOTEMS_NOT_IN_PLAY = 44
    REQ_MINIMUM_TOTAL_MINIONS = 45
    REQ_MUST_TARGET_TAUNTER = 46
    REQ_UNDAMAGED_TARGET = 47
    REQ_CAN_BE_TARGETED_BY_BATTLECRIES = 48
    REQ_STEADY_SHOT = 49
    REQ_MINION_OR_ENEMY_HERO = 50
    REQ_TARGET_IF_AVAILABLE_AND_DRAGON_IN_HAND = 51
    REQ_LEGENDARY_TARGET = 52
    REQ_FRIENDLY_MINION_DIED_THIS_TURN = 53
    REQ_FRIENDLY_MINION_DIED_THIS_GAME = 54
    REQ_ENEMY_WEAPON_EQUIPPED = 55
    REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_MINIONS = 56
    REQ_TARGET_WITH_BATTLECRY = 57
    REQ_TARGET_WITH_DEATHRATTLE = 58
    REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_FRIENDLY_SECRETS = 59
    REQ_SECRET_ZONE_CAP_FOR_NON_SECRET = 60
    REQ_TARGET_EXACT_COST = 61
    REQ_STEALTHED_TARGET = 62
    REQ_MINION_SLOT_OR_MANA_CRYSTAL_SLOT = 63
    REQ_MAX_QUESTS = 64
    REQ_TARGET_IF_AVAILABE_AND_ELEMENTAL_PLAYED_LAST_TURN = 65
    REQ_TARGET_NOT_VAMPIRE = 66
    REQ_TARGET_NOT_DAMAGEABLE_ONLY_BY_WEAPONS = 67
    REQ_NOT_DISABLED_HERO_POWER = 68
    REQ_MUST_PLAY_OTHER_CARD_FIRST = 69
    REQ_HAND_NOT_FULL = 70
    REQ_TARGET_IF_AVAILABLE_AND_NO_3_COST_CARD_IN_DECK = 71
    REQ_CAN_BE_TARGETED_BY_COMBOS = 72
    REQ_CANNOT_PLAY_THIS = 73
    REQ_FRIENDLY_MINIONS_OF_RACE_DIED_THIS_GAME = 74
    REQ_TARGET_IF_AVAILABLE_AND_ONLY_EVEN_COST_CARD_IN_DECK = 75
    REQ_TARGET_IF_AVAILABLE_AND_ONLY_ODD_COST_CARD_IN_DECK = 76
    REQ_OPPONENT_PLAYED_CARDS_THIS_GAME = 77
    REQ_LITERALLY_UNPLAYABLE = 78
    REQ_TARGET_IF_AVAILABLE_AND_HERO_HAS_ATTACK = 79
    REQ_FRIENDLY_MINION_OF_RACE_DIED_THIS_TURN = 80
    REQ_TARGET_IF_AVAILABLE_AND_MINIMUM_SPELLS_PLAYED_THIS_TURN = 81
    REQ_FRIENDLY_MINION_OF_RACE_IN_HAND = 82
    REQ_TARGET_IF_AVAILABLE_AND_COST_5_OR_MORE_SPELL_IN_HAND = 83
    REQ_TARGET_IF_AVAILABLE_AND_MIN_MANA_CRYSTAL = 84
    REQ_MINION_ATTACK_LESS_OR_EQUAL_MANA = 85
    REQ_FRIENDLY_DEATHRATTLE_MINION_DIED_THIS_GAME = 86
    REQ_FRIENDLY_LACKEY = 87
    REQ_TARGET_IF_AVAILABLE_AND_FRIENDLY_LACKEY = 88
    REQ_FRIENDLY_REBORN_MINION_DIED_THIS_GAME = 89
    REQ_MINION_DIED_THIS_GAME = 90
    REQ_TARGET_MIN_HEALTH = 91
    REQ_BOARD_NOT_COMPLETELY_FULL = 92
    REQ_TARGET_IF_AVAILABLE_AND_HAS_OVERLOADED_MANA = 93
    REQ_TARGET_IF_AVAILABLE_AND_HERO_ATTACKED_THIS_TURN = 94
    REQ_TARGET_IF_AVAILABLE_AND_DRAWN_THIS_TURN = 95
    REQ_TARGET_IF_AVAILABLE_AND_NOT_DRAWN_THIS_TURN = 96
    REQ_TARGET_NON_TRIPLED_MINION = 97
    REQ_BOUGHT_MINION_THIS_TURN = 98
    REQ_SOLD_MINION_THIS_TURN = 99
    REQ_TARGET_IF_AVAILABLE_AND_PLAYER_HEALTH_CHANGED_THIS_TURN = 100
    REQ_TARGET_IF_AVAILABLE_AND_SOUL_FRAGMENT_IN_DECK = 101
    REQ_DAMAGED_TARGET_UNLESS_COMBO = 102
    REQ_NOT_MINION_DORMANT = 103
    REQ_TARGET_NOT_UNTOUCHABLE = 104
    REQ_TARGET_IF_AVAILABLE_AND_BOUGHT_RACE_THIS_TURN = 105
    REQ_TARGET_IF_AVAILABLE_AND_SOLD_RACE_THIS_TURN = 106
    REQ_NOT_IN_COOLDOWN = 107
    REQ_TARGET_IS_MERC = 108
    REQ_TARGET_IS_NON_MERC = 109
    REQ_TWO_OF_A_KIND = 110
    REQ_HAS_OVERLOADED_MANA = 111
    REQ_LETTUCE_ABILITY_CANNOT_TARGET_OWNER = 112
    REQ_TARGET_NOT_HAVE_TAG = 116
    REQ_TARGET_MUST_HAVE_TAG = 117
    REQ_TRADEABLE = 119
    REQ_NOT_LEGENDARY_TARGET = 123
    REQ_MINIMUM_TAVERN_TIER_LEVEL_TO_PLAY = 128
    REQ_CARD_TAVERN_TIER_LEVEL_TO_PLAY = 129
    REQ_NOT_EXHAUSTED_LOCATION = 130
    REQ_LOCATION_TARGET = 131
    REQ_TARGET_SILVER_HAND_RECRUIT = 132
    REQ_MINIMUM_CORPSES = 133
    REQ_LOCATION_OR_MINION_TARGET = 134
    REQ_CAN_BE_TARGETED_BY_LOCATIONS = 135
    REQ_FORGE = 136
    REQ_HAS_PLAYED_SPELL_THIS_GAME = 137
    REQ_TARGET_IN_HAND = 138  # 目标必须在手牌中
    REQ_TARGET_IS_NON_TITAN = 141
    REQ_TARGET_EXACT_ATTACK = 143
    REQ_DRAG_TO_PLAY = 999
    
    # Fireplace 扩展：多目标支持
    REQ_MULTIPLE_TARGETS = 1000  # 需要选择多个目标
    REQ_TARGET_COUNT = 1001  # 需要选择的目标数量

    # Renamed
    REQ_ENCHANTED_TARGET = REQ_MAX_SECRETS
    REQ_ENTIRE_ENTOURAGE_NOT_IN_PLAY = REQ_ALL_BASIC_TOTEMS_NOT_IN_PLAY
    REQ_UNIQUE_SECRET = REQ_UNIQUE_SECRET_OR_QUEST
    REQ_SECRET_CAP = REQ_SECRET_ZONE_CAP
    REQ_SECRET_CAP_FOR_NON_SECRET = REQ_SECRET_ZONE_CAP_FOR_NON_SECRET
    REQ_TARGET_NOT_DORMANT = REQ_TARGET_NOT_UNTOUCHABLE


class BoardEnum(IntEnum):
    STORMWIND = 1
    ORGRIMMAR = 2
    PANDARIA = 3
    STRANGLETHORN = 4
    NAXXRAMAS = 5
    GOBLINS_VS_GNOMES = 6
    BLACKROCK_MOUNTAIN = 7
    THE_GRAND_TOURNAMENT = 8
    EXCAVATION_SITE = 9
    THE_MUSEUM = 10
    WHISPERS_OF_THE_OLD_GODS = 11
    KARAZHAN = 12
    GADGETZAN = 13
    UNGORO = 14
    ICECROWN_CITADEL = 15
    THE_CATACOMBS = 16
    THE_WITCHWOOD = 17
    THE_BOOMSDAY_PROJECT = 18
    GURUBASHI_ARENA = 19
    DALARAN = 20
    ULDUM_TOMB = 21
    ULDUM_CITY = 22
    DRAGONBLIGHT = 23
    OUTLAND = 24
    # SCHOLOMANCE = 25
    # DARKMOON_FAIRE = 26
    # THE_BARRENS = 27
    # UNITED_IN_STORMWIND = 28
    # ALTERAC_VALLEY = 29
    # THE_SUNKEN_CITY = 30
    # REVENDRETH = 31
    # MARCH_OF_THE_LICH_KING = 32
    # FESTIVAL_OF_LEGENDS = 33
    # TITANS = 34
    # SHOWDOWN_IN_THE_BADLANDS = 35
    # WHIZBANGS_WORKSHOP = 36
